#!/bin/bash

# Julia 8.2.2020
# Quantification with Featurecounts of project:

PROJECT=20190826_AGimenez_FIS_UFred

# Prepare variables
#------------------

path=/bicoh/MARGenomics
DIR=${path}/${PROJECT}

# Prepare folders
#------------------
mkdir $DIR/Analysis/Quantification/logs


#====================#
#   FeatureCouns     #
#====================#
cd $DIR/Analysis/Quantification

mkdir $DIR/Analysis/Quantification/CountFiles


BAMDIR=$DIR/Analysis/ReadMapping/STAR_BAM_Merged
OUTDIR=$DIR/Analysis/Quantification/CountFiles

sbatch $DIR/Analysis/Quantification/feature.counts.sh $BAMDIR $OUTDIR

#=================#
#   MultiQC       #
#=================#
# Copy CountsTable.txt.summary to multiqc folder
cp $DIR/Analysis/Quantification/CountFiles/CountsTable.txt.summary $DIR/QC/multiQC/

cd $DIR/QC
module load Python/3.5.2-foss-2016b

multiqc . -o $DIR/QC/multiQC -f



