#!/bin/bash

# Júlia 05.08.2022
# Quantification with Featurecounts of project:


PROJECT="project_name"

# Prepare variables
#------------------

path=/bicoh/MARGenomics
DIR=${path}/${PROJECT}

# Prepare folders
#------------------
mkdir $DIR/Analysis/Quantification/logs

#====================#
#   FeatureCouns MM  #
#====================#
BATCH="Batch_01"
sbatch $DIR/Analysis/Quantification/feature.counts.sh $PROJECT $BATCH

#=================#
#   MultiQC       #
#=================#
# Copy CountsTable.txt.summary to multiqc folder
cp $DIR/Analysis/Quantification/CountFiles/CountsTable.txt.summary $DIR/QC/multiQC/

cd $DIR/QC
module load Python/3.5.2-foss-2016b

multiqc . -o $DIR/QC/multiQC -f



