#!/bin/bash

# Julia 8.2.2020
# BAM alignement of project:

PROJECT=20190826_AGimenez_FIS_UFred

# Prepare variables
#------------------

path=/bicoh/MARGenomics
DIR=${path}/${PROJECT}

# Prepare folders
#------------------
mkdir $DIR/ReadMapping/logs


#############################################################################################
#################################TARGET PREPARATION##########################################
cd $DIR/rawData/results-run1
ls -d "$PWD"/*fastq.gz | sed 's/................$//' | sort -u > $DIR/Targets_Fastq

cd $DIR/rawData/results-run2
ls -d "$PWD"/*fastq.gz | sed 's/................$//' | sort -u >> $DIR/Targets_Fastq
#############################################################################################
#############################################################################################

#============#
#   STAR     #
#============#
mkdir $DIR/ReadMapping/BAM_Files

for i in $(cat $DIR/Targets_Fastq | grep -v "Undetermined") 
	do
	echo $i
	OUTDIR=$DIR/ReadMapping/BAM_Files
	sbatch $DIR/ReadMapping/STAR.alignment.sh $i $OUTDIR
	sleep 1
done


#############################################################################################
#Inspect alignment results

OUTDIR=$DIR/ReadMapping/BAM_Files

for i in $OUTDIR/*.final.out; do basename $i >> $OUTDIR/TotalCounts_Alignment; \
grep "Number of input reads" "$i" >> $OUTDIR/TotalCounts_Alignment; grep "Uniquely mapped reads" "$i"\
 >> $OUTDIR/TotalCounts_Alignment; grep "Average mapped length" "$i" >> $OUTDIR/TotalCounts_Alignment;\
 grep "reads mapped to too many loci" "$i" >> $OUTDIR/TotalCounts_Alignment; grep "too many mismatches" "$i"\
 >> $OUTDIR/TotalCounts_Alignment; grep "too short" "$i" >> $OUTDIR/TotalCounts_Alignment;\
 grep "other" "$i" >> $OUTDIR/TotalCounts_Alignment; done


#############################################################################################
#################################TARGET MERGE BAM ##########################################
##################################################################################################

# Targets file removing lane information (one row per sample)
cd $DIR/ReadMapping/BAM_Files
ls -d "$PWD"/*out.bam | sed 's/_L00.*Aligned.sortedByCoord.out.bam$//'  | sort -u > $DIR/ReadMapping/Targets_BamtoMerge_star

#=================#
#   Merge BAMS    #
#=================#

cd $DIR/ReadMapping
mkdir $DIR/ReadMapping/STAR_BAM_Merged

for i in $(cat $DIR/ReadMapping/Targets_BamtoMerge_star) 
	do
	echo $i
	OUTDIR=$DIR/ReadMapping/STAR_BAM_Merged
	sbatch $DIR/ReadMapping/Merge_BAM_Lanes.sh $i $OUTDIR
	sleep 1
done

