#!/bin/bash

# Júlia 5.08.2022 

#################################### BAM alignement of project:  #################################################

PROJECT="project_name"

# Prepare variables
#------------------

path=/bicoh/MARGenomics
DIR=${path}/${PROJECT}

# Prepare folders
#------------------
cd $DIR/Analysis/ReadMapping
mkdir $DIR/Analysis/ReadMapping/logs


suffix=_R1.fastq.gz
BATCH="Batch_01"
length_files=$(ls -1 $DIR/rawData/${BATCH}/*$suffix| wc -l)
sbatch --array=1-$length_files $DIR/Analysis/ReadMapping/STAR.alignment.sh .sh $PROJECT $BATCH $suffix

sbatch $DIR/Analysis/ReadMapping/ReadMapping_metrics.sh $PROJECT $BATCH

