#!/bin/bash

# QC Analysis of RNASeq samples of project: 

PROJECT=20190826_AGimenez_FIS_UFred

# Prepare variables
#------------------

path=/bicoh/MARGenomics
DIR=${path}/${PROJECT}
FASTQDIR=${DIR}/rawData

#===========================#
#   FASTQC and  FASTQSCREEN #
#===========================#
sbatch $DIR/QC/QC_loop.sh


#=================#
#   MultiQC       #
#=================#
mkdir $DIR/QC/multiQC

cd $DIR/QC
module load Python/3.5.2-foss-2016b

multiqc . -f -o $DIR/QC/multiQC

