#!/bin/bash

# QC Analysis of RNASeq samples of project: 

PROJECT=20190826_AGimenez_FIS_UFred

# Prepare variables
#------------------

path=/bicoh/MARGenomics
DIR=${path}/${PROJECT}
FASTQDIR=${DIR}/rawData

#===========================#
#   FASTQC and  FASTQSCREEN #
#===========================#
sbatch $DIR/QC/QC_loop.sh


#===========================#
#   Summarize QC metrics    #
#===========================#
# Runs multiQC and writes excel and figure
sbatch $DIR/QC/QC_metrics.sh

